In [5]:
import numpy as np

In [6]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [7]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [8]:
print(arr.ndim)

3


In [9]:
print(arr[1])

[[1 2 3]
 [4 5 6]]


In [10]:
print(arr[0,1])

[4 5 6]


In [11]:
ar = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [12]:
ar

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
ar[0,1,2]

6

In [14]:
ar1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [15]:
ar1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
ar1[:4]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
a=np.array([1,2,3,4,5])

In [18]:
x=a.copy()

In [19]:
x

array([1, 2, 3, 4, 5])

In [20]:
y=a.view()

In [21]:
y

array([1, 2, 3, 4, 5])

In [22]:
print(x.base)

None


In [23]:
print(y.base)

[1 2 3 4 5]


In [24]:
print(a.shape)

(5,)


In [25]:
k=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [26]:
l=k.reshape(4,3)

In [27]:
l

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
for x in k:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [29]:
for x in l:
    print(x)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [30]:
m = np.array([[1, 2, 3], [4, 5, 6]])
for x in m:
    print(x)

[1 2 3]
[4 5 6]


In [31]:
m= np.array([[1, 2, 3], [4, 5, 6]])
for x in m:
    for y in x:
        print(y)
    

1
2
3
4
5
6


In [32]:
o = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [33]:
for x in o:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [34]:
for x in np.nditer(o):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [35]:
s=np.array([1,2,3])

In [36]:
for x in np.nditer(s,flags=['buffered'],op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [37]:
t = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(t[:, ::2]):
    print(x)

1
3
5
7


In [38]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr2):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [39]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [40]:
arr0

NameError: name 'arr0' is not defined

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2),axis=1)
print(arr)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],
[10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15],
[16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15],
[16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

In [ ]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

In [ ]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

In [ ]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

In [ ]:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

In [ ]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

In [ ]:
arr =np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

In [ ]:
arr = np.array([True, False, True])
print(np.sort(arr))

In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

In [ ]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

In [ ]:
print("hello")

In [42]:
arr = np.array([41, 42, 43, 44])
filter_arr = []
for element in arr:
     if element > 42:
        filter_arr.append(True)
     else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)   

[False, False, True, True]
[43 44]


In [43]:
dt= np.dtype([('name', (np.str_, 10)), ('age',np.int32), ('weight', np.float64)])
a = np.array([('Sana', 2, 21.0), ('Mansi', 7, 29.0)],
dtype=dt)
print(a)

[('Sana', 2, 21.) ('Mansi', 7, 29.)]


In [44]:
b = np.sort(a, order='name')

print('Sorting according to the name', b)

Sorting according to the name [('Mansi', 7, 29.) ('Sana', 2, 21.)]


In [45]:
b = np.sort(a, order='age')

print('\nSorting according to the age', b)


Sorting according to the age [('Sana', 2, 21.) ('Mansi', 7, 29.)]


In [46]:
max_age = np.max(a['age'])
min_age = np.min(a['age'])
print("Max age = ",max_age)
print("Min age = ", min_age)

Max age =  7
Min age =  2


In [48]:
b = np.array([('Ayushi', 5, 30.0)], dtype=a.dtype)
c = np.concatenate((a, b))

In [49]:
print(c)

[('Sana', 2, 21.) ('Mansi', 7, 29.) ('Ayushi', 5, 30.)]


In [50]:
a = np.array([('Sana', 2, 21.0), ('Mansi', 7, 29.0)],
dtype=[('name', (np.str_, 10)), ('age', np.int32),
('weight', np.float64)])
reshaped_a = np.reshape(a, (2, 1))
print(reshaped_a)

[[('Sana', 2, 21.)]
 [('Mansi', 7, 29.)]]


In [51]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
select_elements = array1[[1, 2, 5, 7]]
print(select_elements)

[2 3 6 8]


In [52]:
simple_indexing = array1[3]
print("Simple Indexing:",simple_indexing) # 4
# select multiple elements
fancy_indexing = array1[[1, 2, 5, 7]]
print("Fancy Indexing:",fancy_indexing)

Simple Indexing: 4
Fancy Indexing: [2 3 6 8]


In [56]:
array1 = np.array([3, 2, 6, 1, 8, 5, 7, 4])
sorted_array = array1[np.argsort(array1)]
print(sorted_array)

[1 2 3 4 5 6 7 8]


In [57]:
array1 = np.array([3, 2, 6, 1, 8, 5, 7, 4])
# create a list of indices to assign new values
indices = [1, 3, 6]
# create a new array of values to assign
new_values = [10, 20, 30]
# use fancy indexing to assign new values to specific elements
array1[indices] = new_values
print(array1)

[ 3 10  6 20  8  5 30  4]


In [58]:
array1 = np.array([[1, 3, 5], [11, 7, 9], [13, 18, 29]])
# create an array of row indices
row_indices = np.array([0, 2])
# use fancy indexing to select specific rows
selected_rows = array1[row_indices, :]
print(selected_rows)

[[ 1  3  5]
 [13 18 29]]


In [59]:
import random

In [60]:
random_number = np.random.randint(0, 10)
print(random_number)

6


In [61]:
random_number = np.random.rand()

print(random_number)

0.9745490072221238


In [62]:
integer_array = np.random.randint(0, 10, 5)

print("1D Random Integer Array:\n",integer_array)

1D Random Integer Array:
 [4 9 2 1 4]


In [63]:
float_array = np.random.rand(5)
print("\n1D Random Float Array:\n",float_array)


1D Random Float Array:
 [0.28372422 0.55317197 0.01595683 0.59127414 0.06545062]


In [64]:
result = np.random.randint(0, 10, (3,4))

print("\n2D Random Integer Array:\n",result)


2D Random Integer Array:
 [[5 5 5 6]
 [8 4 5 2]
 [4 0 4 4]]


In [65]:
# create an array of integers from 1 to 5
array1 = np.array([1, 2, 3, 4, 5])
# choose a random number from array1
random_choice = np.random.choice(array1)
print(random_choice)

3


In [66]:
array1 = np.array([1, 3, 5])
array2 = np.array([2, 4, 6])
# use of dot() to perform array multiplication
result = np.dot(array1, array2)
print(result)

44


In [67]:
array1 = np.array([[1, 3], [5, 7]])
array2 = np.array([[2, 4], [6, 8]])
# inner() for 2D arrays
result = np.inner(array1, array2)
print(result)

[[14 30]
 [38 86]]


In [68]:
data = np.array([5, 10, 15, 18, 20])
# createbin to set the interval
bin = [0,10,20,30]
# create histgram
graph = np.histogram(data, bin)
print(graph)
ace(array1)
print(result)

(array([1, 3, 1], dtype=int64), array([ 0, 10, 20, 30]))


NameError: name 'ace' is not defined